sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull debian:stable-slim

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-hldms --tag lacledeslan/gamesvr-hldms --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" ./linux
  - docker run -it --rm lltest/gamesvr-hldms ./ll-tests/gamesvr-hldms.sh

notifications:
  slack:
    secure: yplaIdnHLC0Olzl3iepvBk72Il4vkOgcIijB5B9NV2wV457mA/pFK9BSplIZV/BvIN76FGCIUCAP46f0Q7SL9DN6hYfv6jRLyUtBXWacHVAM+veJoaBLVjN7Hz2dA2emEorNC3X8DH2wqG/0RuyFjLxuAf+5Xb15UU5Q+G2sTIsYmSD/rFzdann9mxV1UBe+XxQeO11185wA9bDt1rDeB3qgnRfpmoqo2snh5bPRRGNNmJl2Xe9djbs5kHyDre49L7EHgKmYoxX2nxdkIdpahUrS3G+Wj9iKtSm7aD37gj3LJiZWSLQNGpflAdiEHoT1NkodD3NkiO9w85bPLnSJS0OsVCklkaUUih7JEsuONf1qkC11cdQmUTSdBNzxaI5jvuia4TFIPj/kRHTjBBVnM98sJnx6MwIhIXTm0Es/lEm963VtqhyRyK23ggBkQG5DihSIyffIw/r4VMwfTZT3b8qR1Gc7DAHKPmY7sFGJrUIyh3Sp+19M9B626E5qBlZ0+ZsZfyAG0tYe4ihFLFZniN0FqKf/BhVmNXwfkpHL0D+2AGR6VK3ATID4GcNFIiQpVZo7f/pZtg1V1mDoUTfDy4084k0A2j/HdxfKbVnFRM3Qgy0tVEeaY3+vKS4+P3GqExKoItXphHXet1sAHqH560sYfs1qpPaokw/fRS/BcZE=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-hldms
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-hldms/$MICROBADGER_TOKEN
  - sh ./.travis/trigger-travis.sh LacledesLAN gamesvr-hldms-freeplay $TRAVIS_ACCESS_TOKEN
